generator: admingenerator.generator.propel
params:
    model: Invision\SoporteBundle\Model\TipoSede
    namespace_prefix: Invision
    concurrency_lock: ~
    bundle_name: SoporteBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete:
            icon: fa fa-eraser
            route: eliminar_tipo_sede
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Tipos de sede
            display: [nombre]
            actions:
                nuevo:
                    icon: fa fa-plus
                    route: nuevo_tipo_sede
                    class: btn btn-primary
            object_actions:
                edit:
                    icon: fa fa-pencil
                    route: editar_tipo_sede
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: []
    new:
        params:
            title: New object for SoporteBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: TipoSede.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: TipoSede.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
