<?php

namespace Invision\SoporteBundle\Model\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'usuario' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Aug 13 05:38:47 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Invision.SoporteBundle.Model.map
 */
class UsuarioTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Invision.SoporteBundle.Model.map.UsuarioTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('usuario');
        $this->setPhpName('Usuario');
        $this->setClassname('Invision\\SoporteBundle\\Model\\Usuario');
        $this->setPackage('src.Invision.SoporteBundle.Model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('nombre', 'Nombre', 'VARCHAR', false, 45, null);
        $this->addColumn('email', 'Email', 'VARCHAR', false, 100, null);
        $this->addColumn('salt', 'Salt', 'VARCHAR', false, 255, null);
        $this->addColumn('apellido', 'Apellido', 'VARCHAR', false, 45, null);
        $this->addColumn('dpi', 'Dpi', 'VARCHAR', false, 255, null);
        $this->addForeignKey('perfil_id', 'PerfilId', 'INTEGER', 'perfil', 'id', true, null, null);
        $this->addColumn('username', 'Username', 'VARCHAR', true, 45, null);
        $this->addColumn('password', 'Password', 'VARCHAR', true, 45, null);
        $this->addColumn('direccion', 'Direccion', 'VARCHAR', false, 100, null);
        $this->addColumn('fecha_nacimiento', 'FechaNacimiento', 'DATE', false, null, null);
        $this->addColumn('ultimo_cambio_password', 'UltimoCambioPassword', 'DATE', false, null, null);
        $this->addForeignKey('sede_id', 'SedeId', 'INTEGER', 'sede', 'id', true, null, null);
        $this->addColumn('created_by', 'CreatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('updated_by', 'UpdatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('created_at', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('updated_at', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Perfil', 'Invision\\SoporteBundle\\Model\\Perfil', RelationMap::MANY_TO_ONE, array('perfil_id' => 'id', ), null, null);
        $this->addRelation('Sede', 'Invision\\SoporteBundle\\Model\\Sede', RelationMap::MANY_TO_ONE, array('sede_id' => 'id', ), null, null);
        $this->addRelation('Maleta', 'Invision\\InventarioBundle\\Model\\Maleta', RelationMap::ONE_TO_MANY, array('id' => 'usuario_id', ), null, null, 'Maletas');
        $this->addRelation('UsuarioHorario', 'Invision\\SoporteBundle\\Model\\UsuarioHorario', RelationMap::ONE_TO_MANY, array('id' => 'usuario_id', ), 'CASCADE', 'CASCADE', 'UsuarioHorarios');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' =>  array (
  'create_column' => 'created_at',
  'update_column' => 'updated_at',
  'disable_updated_at' => 'false',
),
        );
    } // getBehaviors()

} // UsuarioTableMap
