<?php

namespace Invision\InventarioBundle\Model\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'inventario' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Aug 13 05:38:47 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Invision.InventarioBundle.Model.map
 */
class InventarioTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Invision.InventarioBundle.Model.map.InventarioTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('inventario');
        $this->setPhpName('Inventario');
        $this->setClassname('Invision\\InventarioBundle\\Model\\Inventario');
        $this->setPackage('src.Invision.InventarioBundle.Model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('codigo', 'Codigo', 'VARCHAR', true, 100, null);
        $this->addForeignKey('color_id', 'ColorId', 'INTEGER', 'color', 'id', true, null, null);
        $this->addColumn('cantidad', 'Cantidad', 'INTEGER', true, null, null);
        $this->addColumn('costo', 'Costo', 'DOUBLE', true, null, null);
        $this->addColumn('venta', 'Venta', 'DOUBLE', true, null, null);
        $this->addColumn('descripcion', 'Descripcion', 'LONGVARCHAR', false, null, null);
        $this->addColumn('imagen', 'Imagen', 'LONGVARCHAR', false, null, null);
        $this->addForeignKey('sede_id', 'SedeId', 'INTEGER', 'sede', 'id', true, null, null);
        $this->addColumn('created_by', 'CreatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('updated_by', 'UpdatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('created_at', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('updated_at', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Color', 'Invision\\InventarioBundle\\Model\\Color', RelationMap::MANY_TO_ONE, array('color_id' => 'id', ), null, null);
        $this->addRelation('Sede', 'Invision\\SoporteBundle\\Model\\Sede', RelationMap::MANY_TO_ONE, array('sede_id' => 'id', ), null, null);
        $this->addRelation('MaletaDetalle', 'Invision\\InventarioBundle\\Model\\MaletaDetalle', RelationMap::ONE_TO_MANY, array('id' => 'inventario_id', ), 'CASCADE', null, 'MaletaDetalles');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' =>  array (
  'create_column' => 'created_at',
  'update_column' => 'updated_at',
  'disable_updated_at' => 'false',
),
        );
    } // getBehaviors()

} // InventarioTableMap
