<?php

namespace Invision\InventarioBundle\Model\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'material_proceso_extra' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Aug 13 05:38:47 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Invision.InventarioBundle.Model.map
 */
class MaterialProcesoExtraTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Invision.InventarioBundle.Model.map.MaterialProcesoExtraTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('material_proceso_extra');
        $this->setPhpName('MaterialProcesoExtra');
        $this->setClassname('Invision\\InventarioBundle\\Model\\MaterialProcesoExtra');
        $this->setPackage('src.Invision.InventarioBundle.Model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('material_id', 'MaterialId', 'INTEGER', 'material', 'id', true, null, null);
        $this->addForeignKey('proceso_extra_id', 'ProcesoExtraId', 'INTEGER', 'proceso_extra', 'id', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Material', 'Invision\\InventarioBundle\\Model\\Material', RelationMap::MANY_TO_ONE, array('material_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('ProcesoExtra', 'Invision\\InventarioBundle\\Model\\ProcesoExtra', RelationMap::MANY_TO_ONE, array('proceso_extra_id' => 'id', ), 'CASCADE', null);
    } // buildRelations()

} // MaterialProcesoExtraTableMap
