<?php

namespace Invision\InventarioBundle\Model\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'proceso_extra' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Aug 13 05:38:47 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Invision.InventarioBundle.Model.map
 */
class ProcesoExtraTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Invision.InventarioBundle.Model.map.ProcesoExtraTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('proceso_extra');
        $this->setPhpName('ProcesoExtra');
        $this->setClassname('Invision\\InventarioBundle\\Model\\ProcesoExtra');
        $this->setPackage('src.Invision.InventarioBundle.Model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('nombre', 'Nombre', 'VARCHAR', true, 255, null);
        $this->addColumn('descripcion', 'Descripcion', 'LONGVARCHAR', false, null, null);
        $this->addColumn('costo', 'Costo', 'DOUBLE', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('MaterialProcesoExtra', 'Invision\\InventarioBundle\\Model\\MaterialProcesoExtra', RelationMap::ONE_TO_MANY, array('id' => 'proceso_extra_id', ), 'CASCADE', null, 'MaterialProcesoExtras');
    } // buildRelations()

} // ProcesoExtraTableMap
